version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "your_port:your_port"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - cache_network

  cache:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=your_port
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - CACHE_STRATEGY=redis
      - CACHE_PREFIX=speedy:
      - CACHE_TTL=3600
    depends_on:
      - redis
    networks:
      - cache_network

networks:
  cache_network:
    driver: bridge

volumes:
  redis_data: 