SET FOREIGN_KEY_CHECKS = 0;
SELECT CONCAT('DROP TABLE IF EXISTS `', table_name, '`;')
FROM information_schema.tables
WHERE table_schema = DATABASE();
SET FOREIGN_KEY_CHECKS = 1;

DROP TABLE IF EXISTS `attendance_rules`;
DROP TABLE IF EXISTS `attendances`;
DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `classes`;
DROP TABLE IF EXISTS `configs`;
DROP TABLE IF EXISTS `course_enrollments`;
DROP TABLE IF EXISTS `course_materials`;
DROP TABLE IF EXISTS `course_schedules`;
DROP TABLE IF EXISTS `courses`;
DROP TABLE IF EXISTS `departments`;
DROP TABLE IF EXISTS `enrollment_periods`;
DROP TABLE IF EXISTS `enrollment_rules`;
DROP TABLE IF EXISTS `evaluation_indicators`;
DROP TABLE IF EXISTS `evaluation_records`;
DROP TABLE IF EXISTS `evaluation_rules`;
DROP TABLE IF EXISTS `exam_records`;
DROP TABLE IF EXISTS `exams`;
DROP TABLE IF EXISTS `feedback_replies`;
DROP TABLE IF EXISTS `grade_items`;
DROP TABLE IF EXISTS `grade_rules`;
DROP TABLE IF EXISTS `grades`;
DROP TABLE IF EXISTS `majors`;
DROP TABLE IF EXISTS `menus`;
DROP TABLE IF EXISTS `notification_records`;
DROP TABLE IF EXISTS `notifications`;
DROP TABLE IF EXISTS `parent_feedbacks`;
DROP TABLE IF EXISTS `parents`;
DROP TABLE IF EXISTS `permissions`;
DROP TABLE IF EXISTS `questions`;
DROP TABLE IF EXISTS `role_permissions`;
DROP TABLE IF EXISTS `roles`;
DROP TABLE IF EXISTS `semesters`;
DROP TABLE IF EXISTS `student_answers`;
DROP TABLE IF EXISTS `student_behaviors`;
DROP TABLE IF EXISTS `student_courses`;
DROP TABLE IF EXISTS `student_grades`;
DROP TABLE IF EXISTS `student_status_records`;
DROP TABLE IF EXISTS `students`;
DROP TABLE IF EXISTS `system_logs`;
DROP TABLE IF EXISTS `teacher_attendances`;
DROP TABLE IF EXISTS `teacher_courses`;
DROP TABLE IF EXISTS `teacher_title_records`;
DROP TABLE IF EXISTS `teachers`;
DROP TABLE IF EXISTS `teaching_plan_details`;
DROP TABLE IF EXISTS `teaching_plans`;
DROP TABLE IF EXISTS `teaching_schedules`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `users_roles`;
